FirstBlog/FirstBlog/urls.py
from django.conf.urls import patterns, include, url 
from blog import views

urlpatterns = patterns('', 
	
	url(r'^$', 'blog.views.home', name='home'),
	url(r'^index.html', 'blog.views.index', name='index'),
	url(r'^contributors.html', 'blog.views.contributors', name='contributors'),
	url(r'^documents.html', 'blog.views.docs', name='docs'),
	url(r'^contact.html', 'blog.views.contact', name='contact'),
	url(r'^keelcooler.html$', 'blog.views.keelcooler',name='keelcooler'),
	url(r'^result.html$', 'blog.views.formview',name='formview'),
	url(r'^demo_form.asp', 'blog.views.formr', name='formr'),
)

FirstBlog/blog/models.py
from django.db import models

# Create your models here.

class posts(models.Model): 
	
	author = models.CharField(max_length = 30) 
	title = models.CharField(max_length = 100) 
	bodytext = models.TextField() 
	timestamp = models.DateTimeField() 

FirstBlog/blog/forms.py
from django import forms
import math, os, re 



class CommentForm(forms.Form):
	x=150  
#	name = forms.CharField(label='Your name')
#	url = forms.URLField(label='Your website', required=False)
#f = CommentForm(auto_id=False)
#print(f)
#		value = forms.IntegerField(initial = x)

FirstBlog/blog/views.py
from django.shortcuts import render_to_response, render
from blog.models import posts
from .forms import CommentForm
import json
from django import forms
from math import sqrt, acos, log

	 
def QSK19(flowpaths ):
	Qout= 27273/flowpaths #heat dissipation per flow path BTU/min 
	Tin=120 #temperature of coolant into keel cooler in deg False
	Volume_rate=82/448.833/flowpaths #volumetric flow rate in ft^3/s
	QSK19_results=[Qout,Tin,Volume_rate]
	return(QSK19_results) 
	

	
def Resistance1(area,bf,tw,tf,d,L,Tin,Volume_rate):
	a1=(bf-tw)/12#inside height in feet
	b1=(d-2*tf)/12#inside width in feet
	Dh=4*(a1*b1)/(2*a1+b1)
	As1=(2*a1+b1)*L #inside surface area in ft^2
	Ac=(d*bf-area)
	k1=-0.000002*Tin**2+0.0009*Tin+0.2935#thermal conductivity of water in BTU/hr-F-ft-F
	p1=(-0.00007*Tin**2+0.0009*Tin+62.557)#density in lbm/ft^3
	u1=(0.00002*Tin**2-0.0088*Tin+1.1442)*0.001#absolute viscosity in lbm/ft sec
	v1=u1/p1#kinematic viscosity in ft^2/sec
	Cp1=1 #Specific Heat in Btu/lbmF
	Pr1= Cp1*u1/(k1/60**2) #Prandtl number
	V=Volume_rate/(a1*b1)#fluid velocity in ft/s
	Re1=V*L/v1 #Reynolds Number
	Nu1=0.036*Re1**0.8*Pr1**(1/3)
	hc=0.023*k1*(V**0.8)*((u1/p1)**-0.8)*(Dh**(-0.2))	
	d_eqo=(4*Ac/acos(-1))**0.5
	d_eqi=d_eqo-2*tw
	R1=d_eqo/d_eqi*0.0005+1/hc
	Resistance1_results=[R1,hc,k1,d_eqo,d_eqi]
	return(Resistance1_results)
	
def Resistance2(k_material,L, tw):
	R2=tw/12/(k_material)
	return(R2)
	
def Resistance3(L,vessel_speed,tw):
	Tw=85#Degrees Farenheit of water
	k2=-0.000002*Tw**2+0.0009*Tw+0.2935#thermal conductivity of water in BTU/hr-F-ft-F
	p2=(-0.00007*Tw**2+0.0009*Tw+62.557)#density in lbm/ft^3
	u2=(0.00002*Tw**2-0.0088*Tw+1.1442)*0.001#absolute viscosity in lbm/ft sec
	k2=-0.000002*Tw**2+0.0009*Tw+0.2935#thermal conductivity of water in BTU/hr-F-ft-F
	v2=u2/p2
	Cp2=1 #Specific Heat in Btu/lbmF
	Pr2= Cp2*u2/(k2/60**2) #Prandtl number
	ReL=0.65*vessel_speed*1.68*L/v2
	Nu2=0.036*ReL**0.8*Pr2**(1/3)
	ho=k2*Nu2/L
	R3=1/ho
	Resistance3_results=[R3,ho]
	return(Resistance3_results)
	
	
def channel(Channelsize):
	channel_area=[14.7,11.8,9.96,8.82,7.35,6.09,8.82,7.35,5.88,4.49,5.88,4.41,3.94,5.51,4.04,3.38,4.33,3.6,2.87,3.83,3.09,2.4,2.64,1.97,2.13,1.59,1.76,1.47,1.21,10.053,7.036,7.109,5.218,5.927,4.237,4.923,3.526,4.009,2.725,3.427,2.41,2.627,1.881,1.982,1.478,1.358,0.965,0.911,0.491]
	channel_area=channel_area[Channelsize]
	channel_depth=[15.000,15.000,15.000,12.000,12.000,12.000,10.000,10.000,10.000,10.000,9.000,9.000,9.000,8.000,8.000,8.000,7.000,7.000,7.000,6.000,6.000,6.000,5.000,5.000,4.000,4.000,3.000,3.000,3.000,12.000,12.000,10.000,10.000,9.000,9.000,8.000,8.000,7.000,7.000,6.000,6.000,5.000,5.000,4.000,4.000,3.000,3.000,2.000,2.000]
	channel_depth=channel_depth[Channelsize]	
	channel_bf= [3.716,3.520,3.400,3.170,3.047,2.942,3.033,2.886,2.739,2.600,2.648,2.485,2.433,2.527,2.343,2.260,2.299,2.194,2.090,2.157,2.034,1.920,1.885,1.750,1.721,1.584,1.596,1.498,1.410,5.000,4.000,4.250,3.500,4.000,3.250,3.750,3.000,3.500,2.750,3.250,2.500,2.750,2.250,2.250,2.000,1.750,1.500,1.250,1.000]
	channel_bf=channel_bf[Channelsize]
	channel_tf=[0.650,0.650,0.650,0.501,0.501,0.501,0.436,0.436,0.436,0.436,0.413,0.413,0.413,0.390,0.390,0.390,0.366,0.366,0.366,0.343,0.343,0.343,0.320,0.320,0.296,0.296,0.273,0.273,0.273,0.620,0.470,0.500,0.410,0.440,0.350,0.410,0.350,0.380,0.290,0.350,0.290,0.320,0.260,0.290,0.230,0.260,0.200,0.260,0.130]
	channel_tf=channel_tf[Channelsize]
	channel_tw=[0.716,0.520,0.400,0.510,0.387,0.282,0.673,0.526,0.379,0.240,0.448,0.285,0.233,0.487,0.303,0.220,0.419,0.314,0.210,0.437,0.314,0.200,0.325,0.190,0.321,0.184,0.356,0.258,0.170,0.350,0.290,0.310,0.250,0.290,0.230,0.250,0.190,0.210,0.170,0.210,0.170,0.190,0.150,0.190,0.150,0.170,0.130,0.170,0.130]
	channel_tw=channel_tw[Channelsize]
	if Channelsize<29:
		k_material=26.5 #thermal conductivity of Steel BTU/hr-ft-F
	else:
		k_material=118.0 #thermal conductivity of Aluminum BTU/hr-ft-F
	channel_results=[channel_area,channel_depth,channel_tf,channel_bf,channel_tw,k_material]

	return (channel_results)

	
class MyForm(forms.Form):
	Coolant = forms.DecimalField(initial = 1.00)
	Material = forms.DecimalField(initial = 1.00)
	Engineselect = forms.DecimalField(initial = 0.00)
	Channelsize = forms.IntegerField(initial = 1.00)
	flowpaths = forms.IntegerField(initial = 1.00)
	kclength = forms.FloatField(initial = 0.00)
	vessel_speed = forms.FloatField(initial = 0.00)



	
def home(request): 
	return render_to_response( "index.html")
stankogut = "0"
	
	
def index(request):
	template = "index.html"
	content= {'stankogut' : '0'}
	return render_to_response(template, content)
	
def contributors(request):
	entries = posts.objects.all()[:10]
	return render_to_response('contributors.html', {'posts' : entries})

def docs(request):
	entries = posts.objects.all()[:10]
	return render_to_response('documents.html', {'posts' : entries})
	
def contact(request):
	entries = posts.objects.all()[:10]
	return render_to_response('contact.html', {'posts' : entries})


# def keelcooler(request):
	# print(request.POST)
	# form = CommentForm()
	# code1 = form.cleaned_data['code1']
	# context = {"form": form, "xy" : result}
	# template = "keelcooler.html"
	# return render(request, template, context)

# Create your views here.

def keelcooler(request): 
	return render(request, 'keelcooler.html')
	

def formview(request):
	if request.method == 'POST':
		form = MyForm(request.POST)
		if form.is_valid():
			Coolant = form.cleaned_data['Coolant']
			Material = form.cleaned_data['Material']
			Engineselect = form.cleaned_data['Engineselect']
			Channelsize = form.cleaned_data['Channelsize']
			flowpaths = form.cleaned_data['flowpaths']
			kclength = form.cleaned_data['kclength']
			vessel_speed = form.cleaned_data['vessel_speed']
			
			if Engineselect==1:
				QSK19_results=QSK19(flowpaths)
				Qout=QSK19_results[0]
				Tin=QSK19_results[1]
				Volume_rate=QSK19_results[2]
			
			channel_results=channel(Channelsize-1)
			
			L=kclength
			
			
			area=channel_results[0]
			d= channel_results[1]
			bf= channel_results[3]
			tf= channel_results[2]
			tw= channel_results[4]
			k_material= channel_results[5]
			R2=Resistance2(k_material,kclength, tw)
			
			
			Resistance1_results=Resistance1(area,bf,tw,tf,d,kclength,Tin,Volume_rate)
			R1=Resistance1_results[0]
			hi=Resistance1_results[1]
			kw=Resistance1_results[2]
			do_eq=Resistance1_results[3]
			di_eq=Resistance1_results[4]
			
			Resistance3_results=Resistance3(L,vessel_speed,tw)
			R3=Resistance3_results[0]
			ho=Resistance3_results[1]
			
			Rf_seawater=0.0005
			Rf_coolant=0.001
			Cp_eg=-0.0000003*(Tin**2) + 0.0005*(Tin) + 0.7762
			U_overall=1/(R3+Rf_seawater+R2+Rf_coolant+R1)
			
			dT_required= Qout*flowpaths/(Volume_rate*448.833*flowpaths*.1337*64*Cp_eg)
			Th=Tin+dT_required
			Tc=85#Degrees
			
			dTA=Th-Tc
			dTB=Tin-Tc
			LMTD=(dTA-dTB)/log(dTA/dTB)
			A_required=(Qout*flowpaths*60)/(U_overall*LMTD)
			perimeter=(2*bf+d)/12
			A_actual=(perimeter)*L*flowpaths
			
			if(A_actual<A_required):
				KCRESULT="FAIL"
				Lnew=A_required/perimeter/flowpaths
				fpnew=A_required/(perimeter*L)
				if((fpnew-int(fpnew))>0):
					fpnew=int(fpnew)+1
				
				NOTE1="AT THE SAME NUMBER OF FLOW PATHS, THE REQUIRED KEEL COOLER LENGTH IS %.2f ft." %Lnew
				NOTE2="AT THE SAME LENGTH, THE REQUIRED NUMBER OF FLOW PATHS IS %.0f" %fpnew

			else:
				KCRESULT="PASS"
				NOTE1=" "
				NOTE2=" "
			template = "keelcooler.html"
#------------------VARIABLE DEFINITION------------------------------------------------------
			content={
			'Coolant' : Coolant,
			'Material' : Material,
			'Engineselect' : Engineselect,
			'Channelsize' : Channelsize,			
			'flowpaths' : flowpaths,
			'kclength' : kclength,
			'Qout' : Qout,
			'area' : channel_results[0],
			'depth' : channel_results[1],
			'bf' : channel_results[3],
			'tf' : channel_results[2],
			'tw' : channel_results[4],
			'k_material' : channel_results[5], 
			'R1' : R1,
			'hi' : hi,
			'kw' : kw,
			'do_eq' : do_eq,
			'di_eq' : di_eq,
			'R2' : R2,
			'R3' : R3,
			'ho' : ho,
			'U_overall' : U_overall,
			'Temp_increment' : dT_required,
			'LMTD' : LMTD,
			'A_required' : A_required,
			'A_actual' : A_actual,
			'NOTE1' : NOTE1,
			'NOTE2' : NOTE2,
			'KCRESULT' : KCRESULT,
			}
#-------------------------------------------------------------------------------------------
			
			
			
			
#-------------------CALCULATIONS-----------------------

#------------------------------------------------------			

		else:
			template = "keelcooler.html"
			content={
			'message': "[error]"
			}
	return render(request, template, content)
	

FirstBlog/blog/templates/index1firstblog.html
<!DOCTYPE html>

<html lang="en">

<head>
	<meta charset="utf-8" />
	<link rel="stylesheet" href="css/style.css">
	<link href="images/favicon.ico" rel="shortcut icon">
	<title>LOUCE'S FIRST BLOG</title>
</head>

<body>
<div class="container">
	<h1>First Blog</h1>
	
	{% for post in entries %}
		<h2>{{ post.title }}</h2>
		<h3>Posted on {{ post.timestamp }} by {{ post.author }}</h3>
		<p>{{ post.bodytext }}</p>
	{% endfor %}
	
</div>

</body>
</html>

FirstBlog/blog/templates/keelcooler.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/bootstrap.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'blog/bootstrap-responsive.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'blog/bootstrap.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'blog/bootstrap-responsive.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'blog/carousel.css' %}" />


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Senior Design | Cummins</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="../assets/css/bootstrap.css" rel="stylesheet">
    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="css/bootstrap.min.css" rel="stylesheet" media="screen">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  </head>

  <body>



    <!-- NAVBAR
    ================================================== -->
    <div class="navbar-wrapper">
      <!-- Wrap the .navbar in .container to center it within the absolutely positioned parent. -->
      <div class="container">

        <div class="navbar navbar-inverse">
          <div class="navbar-inner">
            <!-- Responsive Navbar Part 1: Button for triggering responsive navbar (not covered in tutorial). Include responsive CSS to utilize. -->
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="brand" href="#">Keel Cooler Optimization Tool</a>
            <!-- Responsive Navbar Part 2: Place all navbar contents you want collapsed withing .navbar-collapse.collapse. -->
            <div class="nav-collapse collapse">
              <ul class="nav">
                <li><a href="index.html">Home</a></li>
                <li><a href="contributors.html">Meet The Team</a></li>
                <li><a href="contact.html">Contact</a></li>
                <li><a href="documents.html">Documents</a></li>
				<li  class="active"><a href="keelcooler.html">Keel Cooler Tool 1.0</a></li>
                <!-- Read about Bootstrap dropdowns at http://twbs.github.com/bootstrap/javascript.html#dropdowns -->
                  </ul>
                </li>
              </ul>
            </div><!--/.nav-collapse -->
          </div><!-- /.navbar-inner -->
        </div><!-- /.navbar -->

      </div> <!-- /.container -->
    </div><!-- /.navbar-wrapper -->



    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide">
      <div class="carousel-inner">
        <div class="item active">
          <img src="{% static "img/ship3.jpg" %}"" alt="">
          <div class="container">
          </div>
        </div>
        <div class="item">
          <img src="{% static "img/CUMMINS2.jpg" %}"" alt="">
          <div class="container">
            <div class="carousel-caption">
              <h1></h1>
              <p class="lead"></p>
            </div>
          </div>
        </div>
        <div class="item">
 <img src="{% static "img/CUMMINS3.jpg" %}"" alt="">
          <div class="container">
            <div class="carousel-caption">
              <h1></h1>
              <p class="lead"></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div><!-- /.carousel -->




    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->


      <!-- Three columns of text below the carousel -->



      <!-- START THE FEATURETTES

      <hr class="featurette-divider">-->

    <div class="row">
				<form action="result.html" method="POST"> {% csrf_token %}
					<p>
					<div class="ui-widget">
					<h1>Welcome to the Keel Cooler Tool 1.0</h1>
					<p>Please select an engine, coolant, material, channel size and flowpaths to receive the proper measurement of heat dissipation.</b>
					<br><br>
					<label for="id_Engineselect"><h4>Engine Selection:</h4></label>	
						<center>
						  <input id="id_Engineselect" type="radio" name="Engineselect" value=1 checked> QSK19 <img src="{% static "img/engines/QSK19.jpg" %}"" alt=""> 
						  <input id="id_Engineselect" type="radio" name="Engineselect" value=2> QSK38 <img src="{% static "img/engines/QSK38.jpg" %}"" alt=""> 
						  <input id="id_Engineselect" type="radio" name="Engineselect" value=3> QSK50 <img src="{% static "img/engines/QSK50.jpg" %}"" alt=""> 
						  <input id="id_Engineselect" type="radio" name="Engineselect" value=4> QSK60 <img src="{% static "img/engines/QSK60.jpg" %}"" alt=""> 
						</center>
					</div>

					<br>
					<label for="id_Coolant"><h4>Coolant: </h4></label>
						<select for="id_Coolant" name="Coolant">
						  <option id="id_Coolant" value=1>50/50 Glycol</option>
						  <option id="id_Coolant" value=2>Water/DCA</option>
						</select>
					<br>
					<label for="id_Material"><h4>Channel Material: </h4></label>
						<select for="id_Material" name="Material">
						  <option id="id_Material" value=1>Steel</option>
						  <option id="id_Material" value=2>Aluminum</option>
						</select>
					<br>
					<label for="id_Channelsize"><h4>Channel Size: </h4></label>
						<select for="id_Channelsize" name="Channelsize">
						<optgroup label="Steel">
							<option id="id_Channelsize" value=1>C15 × 50</option>
								<option id="id_Channelsize" value=2>C15 × 40</option>
								<option id="id_Channelsize" value=3>C15 × 33.9</option>
								<option id="id_Channelsize" value=4>C12 × 30</option>
								<option id="id_Channelsize" value=5>C12 × 25</option>
								<option id="id_Channelsize" value=6>C12 × 20.7</option>
								<option id="id_Channelsize" value=7>C10 × 30</option>
								<option id="id_Channelsize" value=8>C10 × 25</option>
								<option id="id_Channelsize" value=9>C10 × 20</option>
								<option id="id_Channelsize" value=10>C10 × 15.3</option>
								<option id="id_Channelsize" value=11>C9 × 20</option>
								<option id="id_Channelsize" value=12>C9 × 15</option>
								<option id="id_Channelsize" value=13>C9 × 13.4</option>
								<option id="id_Channelsize" value=14>C8 × 18.75</option>
								<option id="id_Channelsize" value=15>C8 × 13.75</option>
								<option id="id_Channelsize" value=16>C8 × 11.5</option>
								<option id="id_Channelsize" value=17>C7 × 14.75</option>
								<option id="id_Channelsize" value=18>C7 × 12.25</option>
								<option id="id_Channelsize" value=19>C7 × 9.8</option>
								<option id="id_Channelsize" value=20>C6 × 13</option>
								<option id="id_Channelsize" value=21>C6 × 10.5</option>
								<option id="id_Channelsize" value=22>C6 × 8.2</option>
								<option id="id_Channelsize" value=23>C5 × 9</option>
								<option id="id_Channelsize" value=24>C5 × 6.7</option>
								<option id="id_Channelsize" value=25>C4 × 7.25</option>
								<option id="id_Channelsize" value=26>C4 × 5.4</option>
								<option id="id_Channelsize" value=27>C3 × 6</option>
								<option id="id_Channelsize" value=28>C3 × 5</option>
								<option id="id_Channelsize" value=29>C3 × 4.1</option>

						<optgroup label="Aluminum">
								<option id="id_Channelsize" value=30>12 × 11.822</option>
								<option id="id_Channelsize" value=31>12 × 8.274</option>
								<option id="id_Channelsize" value=32>10 × 8.36</option>
								<option id="id_Channelsize" value=33>10 × 6.136</option>
								<option id="id_Channelsize" value=34>9 × 6.97</option>
								<option id="id_Channelsize" value=35>9 × 4.983</option>
								<option id="id_Channelsize" value=36>8 × 5.789</option>
								<option id="id_Channelsize" value=37>8 × 4.147</option>
								<option id="id_Channelsize" value=38>7 × 4.715</option>
								<option id="id_Channelsize" value=39>7 × 3.205</option>
								<option id="id_Channelsize" value=40>6 × 4.03</option>
								<option id="id_Channelsize" value=41>6 × 2.834</option>
								<option id="id_Channelsize" value=42>5 × 3.089</option>
								<option id="id_Channelsize" value=43>5 × 2.212</option>
								<option id="id_Channelsize" value=44>4 × 2.331</option>
								<option id="id_Channelsize" value=45>4 × 1.738</option>
								<option id="id_Channelsize" value=46>3 × 1.597</option>
								<option id="id_Channelsize" value=47>3 × 1.135</option>
								<option id="id_Channelsize" value=48>2 × 1.071</option>
								<option id="id_Channelsize" value=49>2 × 0.577</option>

						</select>			
						
					<label for="id_flowpaths"><h4>Number of Flow Paths: </h4> </label>
					<input id="id_flowpaths" type="number" name="flowpaths" min="1" max="20" value="3" style="height:30px" />						
					<label for="id_kclength"><h4>Installed Keel Cooler Length: </h4> </label>
					<input id="id_kclength" type="float" name="kclength" min="0" value="100" style="height:30px" />
					<label for="id_vessel_speed"><h4>Vessel Speed (knots): </h4> </label>
					<input id="id_vessel_speed" type="float" name="vessel_speed" min="0" value="3" style="height:30px" />
					

					
					<br><br><input type='submit' value='SUBMIT' class ='btn' />		<div="blank" style="color:red;">{{message}}</div>
					<br><h3>RESULTS: </h3> 
					<p> Qout = {{ Qout }} </p>
					<p> Area = {{area}} </p>
					<p> Depth = {{depth}} </p>
					<p> bf = {{bf}} </p>
					<p> tf = {{tf}} </p>
					<p> tw = {{tw}} </p>
					<p> k_material = {{k_material}} </p>
					<p> hi = {{hi}} </p>
					<p> R1 = {{R1}} </p>
					<p> kw = {{kw}} </p>
					<p> do_eq = {{do_eq}} </p>
					<p> di_eq = {{di_eq}} </p>
					<p> R2 = {{R2}} </p>
					<p> R3 = {{R3}} </p>
					<p> ho = {{ho}} </p>
					<p> Uoverall = {{U_overall}} </p>
					<p> Temp Increment = {{Temp_increment}} </p>
					<p> LMTD = {{LMTD}} </p>
					<p> Area Required = {{A_required}} </p>
					<p> Area Actual = {{A_actual}} </p>
					<br><h3>(PASS/FAIL): {{ KCRESULT }}</h3> 
					<p>{{ NOTE1 }} </p>
					<p>{{ NOTE2 }} </p>
					</div>
					</p>
				</form>

				</body>	
			</div>
      <!-- /END THE FEATURETTES -->


      <!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
		<center>
        <p>&copy; 2016 FSU Senior Design Team 3 | Cummins, Inc.</p>
		</center>
      </footer>

    </div><!-- /.container -->



    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../assets/js/jquery.js"></script>
    <script src="../assets/js/bootstrap-transition.js"></script>
    <script src="../assets/js/bootstrap-alert.js"></script>
    <script src="../assets/js/bootstrap-modal.js"></script>
    <script src="../assets/js/bootstrap-dropdown.js"></script>
    <script src="../assets/js/bootstrap-scrollspy.js"></script>
    <script src="../assets/js/bootstrap-tab.js"></script>
    <script src="../assets/js/bootstrap-tooltip.js"></script>
    <script src="../assets/js/bootstrap-popover.js"></script>
    <script src="../assets/js/bootstrap-button.js"></script>
    <script src="../assets/js/bootstrap-collapse.js"></script>
    <script src="../assets/js/bootstrap-carousel.js"></script>
    <script src="../assets/js/bootstrap-typeahead.js"></script>
    <script>
      !function ($) {
        $(function(){
          // carousel demo
          $('#myCarousel').carousel()
        })
      }(window.jQuery)
    </script>
    <script src="../assets/js/holder/holder.js"></script>
    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>
	<script src="{% static 'blog/bootstrap.min.js' %}""></script>
  </body>
</html>

FirstBlog/blog/templates/result.html
{% load staticfiles %}
{% csrf_token %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/bootstrap.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'blog/bootstrap-responsive.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'blog/bootstrap.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'blog/bootstrap-responsive.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'blog/carousel.css' %}" />

<!DOCTYPE html>
<html lang="en">
  <head>
  </head>
<body>
  <h1>Your Engine is {{ Engine }}</h1>
  <h1>Your Coolant is {{ Coolant }}</h1>
</body>
</html>